#!/bin/sh

export DOCKER_HOST=tcp://$(boot2docker ip 2>/dev/null):2375

# 确保已安装docker-enter
echo "Installing docker-enter..."
declare -F docker-enter || curl -sL https://raw.githubusercontent.com/iamfat/boot2docker-gini/master/docker-enter >> ~/.profile
. ~/.profile

echo "Turn on remote syslog..."
curl -sL https://raw.githubusercontent.com/iamfat/boot2docker-gini/master/remote-syslog | sudo sh

echo "Pulling latest docker images..." 
docker pull iamfat/rsyslog
docker pull iamfat/mariadb
docker pull iamfat/redis
docker pull iamfat/gini-dev
 
echo "Preparing environment..."

: ${BASE_DIR:=/mnt/sda1/data}

# remote logging
boot2docker ssh "sudo mkdir -p $BASE_DIR/etc/rsyslog.d"
boot2docker ssh "sudo echo '*.* @192.168.59.3' | sudo tee $BASE_DIR/etc/rsyslog.d/20-host.conf"
 
# nginx
boot2docker ssh "sudo mkdir -p $BASE_DIR/etc/nginx/sites-enabled"
boot2docker ssh "sudo mkdir -p $BASE_DIR/log/nginx"

echo "Starting containers..."
docker run --name rsyslog --privileged \
    -v /dev:/dev \
    -v $BASE_DIR/etc/rsyslog.d:/etc/rsyslog.d \
    -d iamfat/rsyslog

docker run --name mariadb --privileged \
    -v /dev/log:/dev/log -v $BASE_DIR:/data \
    -d iamfat/mariadb

docker run --name redis --privileged \
    -v /dev/log:/dev/log -v $BASE_DIR:/data \
    -d iamfat/redis

docker run --name gini-dev --privileged \
    -v /dev/log:/dev/log -v $BASE_DIR:/data \
    --link mariadb:mysql --link redis:redis \
    -d iamfat/gini-dev

docker run --name nginx --privileged \
    -v /dev/log:/dev/log -v $BASE_DIR:/data \
    -v $BASE_DIR/etc/nginx/sites-enabled:/etc/nginx/sites-enabled \
    -v $BASE_DIR/var/log/nginx:/var/log/nginx \
    --link gini-dev:gini-dev \
    -p 80:80 \
    -d iamfat/nginx

# make sure PHP session works
docker-enter gini-dev 'sudo chmod a+wt,go-r /var/lib/php5'

echo "Prepare Gini Modules Dir..."
docker-enter gini-dev 'mkdir -p /data/gini-modules'
docker-enter gini-dev '[ -d /data/gini-modules/gini ]' || docker-enter gini-dev 'git clone https://github.com/iamfat/gini /data/gini-modules/gini'
docker-enter gini-dev 'curl -Lo /etc/profile.d/gini.sh https://raw.githubusercontent.com/iamfat/boot2docker-gini/master/gini.sh'

